[project]
name = "manim-animations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.1.0",
    "manimgl>=1.7.1",
    "pyannote-audio>=3.3.2",
]
